# REST Client - https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###

# Get list of all users
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users
authorization: Bearer <access_token>

###

# Get list of all admin users
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/admins
authorization: Bearer <access_token>

###

# Get list of all customers
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/customers
authorization: Bearer <access_token>

###

# Get a specific user
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/5

###

# Create admin
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/create
content-type: application/json

{
    "firstname": "Baby",
    "lastname": "Star",
    "email": "star@gmail.com",
    "type": "Admin",
    "username": "baby",
    "password": "***",
    "federated_login": 0,
    "billing_address": "SG",
    "shipping_address": "SG"
}

###

# Create user
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/create
content-type: application/json

{
    "firstname": "Cherry",
    "lastname": "Blue",
    "email": "blue.cherry@gmail.com",
    "type": "Customer",
    "username": "cherry",
    "password": "***",
    "federated_login": 0,
    "billing_address": "SG",
    "shipping_address": "SG"
}

###

# Get info of authenticated user
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/info
content-type: application/json
authorization: Bearer <access_token>

###

# Update user
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/3/update
content-type: application/json

{
    "firstname": "Alan",
    "lastname": "Tan",
    "email": "email@your-domain.com",
    "type": "Admin",
    "username": null,
    "password": null,
    "federated_login": 0,
    "billing_address": "Orchard Road",
    "shipping_address": "Orchard Road"
}

###

# Delete user

DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/5/delete
authorization: Bearer <access_token>

###

DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/delete
content-type: application/json
authorization: Bearer <access_token>

{
    "password": "***"
}


###

# Authenticate using email/password

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/authenticate
content-type: application/json

{
    "username": "email@your-domain.com",
    "password": "***"
}

###

# Authenticate as admin using username/password

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/authenticate
content-type: application/json

{
    "username": "****",
    "password": "****"
}

###

# Authenticate as customer using username/password

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/authenticate
content-type: application/json

{
    "username": "****",
    "password": "****"
}

###

# Get new access token using refresh token

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/refresh
content-type: application/json

{
    "refresh_token": "***"
}

###

# Logout

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/logout
content-type: application/json
authorization: Bearer <access_token>-WCXF9StXhwvO9J4AljY5sli_o

{
    "refresh_token": "***"
}

###

# Change password

PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/5/change-password
content-type: application/json
authorization: Bearer <access_token>


{
    "current_password": "****",
    "new_password": "****"
}

###

# Get list of all categories
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/categories

###

# Get a specific category
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/categories/6

###

# Create category
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/categories/create
content-type: application/json
authorization: Bearer <access_token>

{
    "name": "Test Shoes"
}

###

# Update category
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/categories/6/update
content-type: application/json
authorization: Bearer <access_token>

{
    "name": "Test Shoes 2"
}

###

# Delete category
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/categories/6/delete
content-type: application/json
authorization: Bearer <access_token>

###

# Get list of all designers
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/designers

###

# Get a specific designer
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/designers/2

###

# Update designer
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/designers/1/update
content-type: application/json

{
    "name": "Prada 1"
}

###

# Delete designer
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/designers/1/delete

###

# Create designer
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/designers/create
content-type: application/json
authorization: Bearer <access_token>

{
    "name": "Dolce Gabbanna"
}

###

# Get list of all insurances
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/insurances

###

# Get a specific insurance
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/insurances/1

###

# Update insurance
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/insurances/1/update
content-type: application/json

{
    "policy_date": "2019-01-29",
    "claim_date": "2020-12-02",
    "coverage_amount": 300
}

###

# Delete a specific insurance
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/insurances/1/delete

###

# Create insurance
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/insurances/create
content-type: application/json

{
    "policy_date": "2019-01-30",
    "claim_date": "2020-12-01",
    "coverage_amount": 350
}

###

# Get list of all products
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products

###

# Get list of all products with search criteria
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products?min_quantity=0

###

# Get list of product conditions
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products/conditions

###

# Get a specific product
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products/4

###

# Update a specific product
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products/2000/update
content-type: application/json
authorization: Bearer <access_token>

{
    "designer_id": 2,
    "category_id": 2,
    "insurance_id": 2,
    "name": "Prada Bag 2011",
    "retail_price": 150,
    "selling_price": 90,
    "description": "XX",
    "specifications": "",
    "condition": "",
    "condition_description": "",
    "sku": "",
    "quantity": 1,
    "authenticity": true,
    "product_image_1": "",
    "product_image_2": "",
    "product_gallery_1": "",
    "product_gallery_2": "",
    "product_gallery_3": "",
    "product_gallery_4": "",
    "product_gallery_5": "",
    "product_gallery_6": "",
    "product_gallery_7": "",
    "product_gallery_8": "",
    "tags": "2"
}



###

# Delete a specific product
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products/3/delete
content-type: application/json
authorization: Bearer <access_token>

###

# Create product
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products/create
content-type: application/json
authorization: Bearer <access_token>

{
    "designer_id": 2,
    "category_id": 2,
    "insurance_id": 2,
    "name": "Prada Bag 2012",
    "retail_price": 155,
    "selling_price": 120,
    "description": "xx",
    "specifications": "",
    "condition": "",
    "condition_description": "",
    "sku": "",
    "quantity": 1,
    "authenticity": true,
    "product_image_1": "",
    "product_image_2": "",
    "product_gallery_1": "",
    "product_gallery_2": "",
    "product_gallery_3": "",
    "product_gallery_4": "",
    "product_gallery_5": "",
    "product_gallery_6": "",
    "product_gallery_7": "",
    "product_gallery_8": "",
    "tags": "2"
}

###

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products/create
content-type: application/json
authorization: Bearer <access_token>

{
    "designer_id":"7",
    "category_id":"4",
    "name":"Xcode",
    "retail_price":"150",
    "selling_price":"120",
    "condition":"Fair",
    "condition_description":"XX",
    "quantity":"1",
    "authenticity": true,
    "product_image_1":"http://res.cloudinary.com/drkdludjy/image/upload/v1638025403/w5a8j0dw7gi6zw63h6bo.jpg",
    "product_image_2":"http://res.cloudinary.com/drkdludjy/image/upload/v1638025415/hvas9dfllubaz40eiihx.jpg",
    "product_gallery_1":"http://res.cloudinary.com/drkdludjy/image/upload/v1638025421/jx1hj1lnqzf4zgw7bnat.jpg",
    "product_gallery_2":"http://res.cloudinary.com/drkdludjy/image/upload/v1638025429/ehyoxaalcn1ayzbibybl.jpg",
    "product_gallery_3":"",
    "product_gallery_4":"",
    "product_gallery_5":"",
    "product_gallery_6":"",
    "product_gallery_7":"",
    "product_gallery_8":"",
    "tags":"1,3"
}

###

# Get list of all tags
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/tags

###

# Get a specific tag
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/tags/1

###

# Create tag
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/tags/create
content-type: application/json
authorization: Bearer <access_token>

{
    "name": "X Collaboration"
}

###

# Update tag
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/tags/2/update
content-type: application/json
authorization: Bearer <access_token>

{
    "name": "New Arrival"
}

###

# Delete tag
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/tags/1/delete
authorization: Bearer <access_token>

###

# Get cart for authenticated user
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/mycart
content-type: application/json
authorization: Bearer <access_token>

###

# Get list of all carts
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/all
authorization: Bearer <access_token>

###

# Get a cart by id 
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/52

###

# Update a cart
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/34/update
content-type: application/json

{
    "items": [
        { "product_id": 1, "quantity": 3 },
        { "product_id": 2, "quantity": 4 }
    ]
}

###

# Create a cart
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/create
content-type: application/json
authorization: Bearer <access_token>-uxI

{
    "items": [
        { "product_id": 2, "quantity": 3 }
    ]
}

###

# Create a cart for anonymous
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/create
content-type: application/json

{
    "items": [
        { "product_id": 2, "quantity": 1 }
    ]
}



###

# Update a user's cart

PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/update
content-type: application/json
authorization: Bearer <access_token>

{
    "items": [
        { "product_id": 4, "quantity": 2 }
    ]
}

###

# Update quantity of a cart item

PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/34/update/2
content-type: application/json

{
    "quantity": 2
}

###

# Update ownership of a cart

PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/35/own
authorization: Bearer <access_token>-a0QUqqA

###

# Delete cart
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/2/delete

###

# Checkout

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/checkout
content-type: application/json
authorization: Bearer <access_token>

{
    "success_url": "https://<your-website>/checkout/success",
    "cancel_url": "https://<your-website>/checkout/error"
}

###

# Get list of all orders
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/orders
authorization: Bearer <access_token>

###

# Get list of all orders with search criteria
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/orders?search=blue.cherry@gmail.com&order_status=paid
authorization: Bearer <access_token>

###

# Get list of valid order statuses
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/orders/statuses

###

# Get list of shipment/courier providers
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/orders/shipment-providers

###

# Get an order
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/orders/3
authorization: Bearer <access_token>

###

# Update an order
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/orders/3
content-type: application/json
authorization: Bearer <access_token>

{
    "status": "Delivered",
    "comment": "Testing 2.."
}

###

# Get all consignments

GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/consignments
content-type: application/json
authorization: Bearer <access_token>


###

# Get valid consignment statuses

GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/consignments/statuses


###

# Create consigment
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/consignments/create
content-type: application/json
authorization: Bearer <access_token>

{
    "designer_id": 2,
    "category_id": 2,
    "name": "Rolex 2012",
    "selling_price": 120,
    "specifications": "45cm by 60cm",
    "condition": "good",
    "condition_description": "Good with no scatches",
    "product_gallery_1": "",
    "product_gallery_2": "",
    "product_gallery_3": "",
    "product_gallery_4": "",
    "product_gallery_5": "",
    "product_gallery_6": "",
    "product_gallery_7": "",
    "product_gallery_8": null
}

###

# Update a consignment
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/consignments/1/update
content-type: application/json
authorization: Bearer <access_token>

{
    "status": "Initial Evaluation",
    "comment": "some comments from evaluation..."
}

###
