# REST Client - https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###

# Get list of all users
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/users

###

# Get list of all admin users
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/users/admins

###

# Get list of all customers
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/users/customers

###

# Get a specific user
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/users/5

###

# Create admin
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/users/create
content-type: application/json

{
    "firstname": "Baby",
    "lastname": "Star",
    "email": "star@gmail.com",
    "type": "Admin",
    "username": "baby",
    "password": "password",
    "federated_login": 0,
    "billing_address": "SG",
    "shipping_address": "SG"
}

###

# Create user
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/users/create
content-type: application/json

{
    "firstname": "Cherry",
    "lastname": "Blue",
    "email": "blue.cherry@gmail.com",
    "type": "Customer",
    "username": "cherry",
    "password": "password",
    "federated_login": 0,
    "billing_address": "SG",
    "shipping_address": "SG"
}

###

# Get info of authenticated user
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/users/info
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6Niwicm9sZSI6IkN1c3RvbWVyIiwiZW1haWwiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoZXJyeSIsImlhdCI6MTYzNzgzNzIzNCwiZXhwIjoxNjM3ODM4MTM0LCJzdWIiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20ifQ.B2QCOau0rSPr-KfoTYivNDA0Pn-ud7jH4DWvTVRYlaE

###

# Update user
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/users/3/update
content-type: application/json

{
    "firstname": "Darren",
    "lastname": "Poh",
    "email": "darpohsh@gmail.com",
    "type": "Admin",
    "username": null,
    "password": null,
    "federated_login": 0,
    "billing_address": "Bedok SG",
    "shipping_address": "SG"
}

###

# Delete user

DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/users/4/delete

###

# Authenticate using email/password

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/users/authenticate
content-type: application/json

{
    "username": "admin@your-company.com",
    "password": "password"
}

###

# Authenticate as admin using username/password

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/users/authenticate
content-type: application/json

{
    "username": "admin",
    "password": "password1"
}

###

# Authenticate as customer using username/password

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/users/authenticate
content-type: application/json

{
    "username": "cherry",
    "password": "password"
}

###

# Get new access token using refresh token

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/users/refresh
content-type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIn0.eyJpZCI6NiwiaWF0IjoxNjM3ODE1NzA0LCJleHAiOjE2Mzg0MjA1MDQsInN1YiI6ImJsdWUuY2hlcnJ5QGdtYWlsLmNvbSJ9.wI3SYtbuTDxZL63fZX4aR_sZLclCJJNOid250qzVjBw"
}

###

# Logout

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/users/logout
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6NSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJzdGFyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYmFieSIsImlhdCI6MTYzNzY1MzE1MCwiZXhwIjoxNjM3NjU0MDUwLCJzdWIiOiJzdGFyQGdtYWlsLmNvbSJ9.59Q90JqeeLHzBZURw-WCXF9StXhwvO9J4AljY5sli_o

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIn0.eyJpZCI6NSwiaWF0IjoxNjM3NjUzMTUwLCJleHAiOjE2MzgyNTc5NTAsInN1YiI6InN0YXJAZ21haWwuY29tIn0.TDolo31kPMmrazMN9Z42yZGAU0jd2OYHJNrbfsHeqnk"
}

###

# Change password

PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/users/5/change-password
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6NSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJzdGFyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYmFieSIsImlhdCI6MTYzNzU5NTMyMiwiZXhwIjoxNjM3NTk2MjIyLCJzdWIiOiJzdGFyQGdtYWlsLmNvbSJ9.BYepT8ScwD06XEZIuXz_hoCACXSbxg-tPRs_YyO-vD4


{
    "current_password": "password1",
    "new_password": "password"
}

###

# Get list of all categories
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/categories

###

# Get a specific category
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/categories/2

###

# Create category
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/categories/create
content-type: application/json

{
    "name": "Shoes"
}

###

# Update category
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/categories/1/update
content-type: application/json

{
    "name": "Shoes 1"
}

###

# Delete category
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/categories/1/delete

###

# Get list of all designers
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/designers

###

# Get a specific designer
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/designers/2

###

# Update designer
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/designers/1/update
content-type: application/json

{
    "name": "Prada 1"
}

###

# Delete designer
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/designers/1/delete

###

# Create designer
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/designers/create
content-type: application/json

{
    "name": "Prada"
}

###

# Get list of all insurances
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/insurances

###

# Get a specific insurance
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/insurances/1

###

# Update insurance
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/insurances/1/update
content-type: application/json

{
    "policy_date": "2019-01-29",
    "claim_date": "2020-12-02",
    "coverage_amount": 300
}

###

# Delete a specific insurance
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/insurances/1/delete

###

# Create insurance
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/insurances/create
content-type: application/json

{
    "policy_date": "2019-01-30",
    "claim_date": "2020-12-01",
    "coverage_amount": 350
}

###

# Get list of all products
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/products

###

# Get a specific product
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/products/4

###

# Update a specific product
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/products/4/update
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6NSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJzdGFyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYmFieSIsImlhdCI6MTYzNzc3MzE5MSwiZXhwIjoxNjM3Nzc0MDkxLCJzdWIiOiJzdGFyQGdtYWlsLmNvbSJ9.t-z6_uhvIQ_1803q4auD9I9fVtAni-ZwMUuZmjHszlE

{
    "designer_id": 2,
    "category_id": 2,
    "insurance_id": 2,
    "name": "Prada Bag 2011",
    "retail_price": 150,
    "selling_price": 90,
    "description": "XX",
    "specifications": "",
    "condition": "",
    "condition_description": "",
    "sku": "",
    "quantity": 1,
    "authenticity": true,
    "product_image_1": "",
    "product_image_2": "",
    "product_gallery_1": "",
    "product_gallery_2": "",
    "product_gallery_3": "",
    "product_gallery_4": "",
    "product_gallery_5": "",
    "product_gallery_6": "",
    "product_gallery_7": "",
    "product_gallery_8": "",
    "tags": "2"
}

###

# Delete a specific product
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/products/4/delete

###

# Create product
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/products/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6NSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJzdGFyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYmFieSIsImlhdCI6MTYzNzY3NjM2OCwiZXhwIjoxNjM3Njc3MjY4LCJzdWIiOiJzdGFyQGdtYWlsLmNvbSJ9.nAm2sM8hytm86CXmi40oi_myMGpN_7P0_A-jq84IBhY

{
    "designer_id": 2,
    "category_id": 2,
    "insurance_id": 2,
    "name": "Prada Bag 2012",
    "retail_price": 155,
    "selling_price": 120,
    "description": "xx",
    "specifications": "",
    "condition": "",
    "condition_description": "",
    "sku": "",
    "quantity": 1,
    "authenticity": true,
    "product_image_1": "",
    "product_image_2": "",
    "product_gallery_1": "",
    "product_gallery_2": "",
    "product_gallery_3": "",
    "product_gallery_4": "",
    "product_gallery_5": "",
    "product_gallery_6": "",
    "product_gallery_7": "",
    "product_gallery_8": "",
    "tags": "2"
}

###

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/products/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODAyNTYxNSwiZXhwIjoxNjM4MDI2NTE1LCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.8S6MMM75F3wXk7yPgEPPYAI9xHuozBrHGj_19URmxj4

{"designer_id":"7","category_id":"4","name":"Xcode","retail_price":"150","selling_price":"120","condition":"Fair","condition_description":"XX","quantity":"1","authenticity":"1","product_image_1":"http://res.cloudinary.com/drkdludjy/image/upload/v1638025403/w5a8j0dw7gi6zw63h6bo.jpg","product_image_2":"http://res.cloudinary.com/drkdludjy/image/upload/v1638025415/hvas9dfllubaz40eiihx.jpg","product_gallery_1":"http://res.cloudinary.com/drkdludjy/image/upload/v1638025421/jx1hj1lnqzf4zgw7bnat.jpg","product_gallery_2":"http://res.cloudinary.com/drkdludjy/image/upload/v1638025429/ehyoxaalcn1ayzbibybl.jpg","product_gallery_3":"","product_gallery_4":"","product_gallery_5":"","product_gallery_6":"","product_gallery_7":"","product_gallery_8":"","tags":"1,3"}

###

# Get list of all tags
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/tags

###

# Get a specific tag
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/tags/1

###

# Create tag
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/tags/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6NSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJzdGFyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYmFieSIsImlhdCI6MTYzNzY3NjM2OCwiZXhwIjoxNjM3Njc3MjY4LCJzdWIiOiJzdGFyQGdtYWlsLmNvbSJ9.nAm2sM8hytm86CXmi40oi_myMGpN_7P0_A-jq84IBhY

{
    "name": "New Arrival"
}

###

# Update tag
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/tags/2/update
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6NSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJzdGFyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYmFieSIsImlhdCI6MTYzNzY2NjA4OSwiZXhwIjoxNjM3NjY2OTg5LCJzdWIiOiJzdGFyQGdtYWlsLmNvbSJ9.o-W2ZluOPTB49b9dYVlUuzA9DLqk7dgW07ZOSdWOyIs

{
    "name": "New Arrival"
}

###

# Delete tag
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/tags/1/delete
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6NSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJzdGFyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYmFieSIsImlhdCI6MTYzNzY2NjA4OSwiZXhwIjoxNjM3NjY2OTg5LCJzdWIiOiJzdGFyQGdtYWlsLmNvbSJ9.o-W2ZluOPTB49b9dYVlUuzA9DLqk7dgW07ZOSdWOyIs

###

# Get cart for authenticated user
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/carts
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6Niwicm9sZSI6IkN1c3RvbWVyIiwiZW1haWwiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoZXJyeSIsImlhdCI6MTYzNzgyMzM3OSwiZXhwIjoxNjM3ODI0Mjc5LCJzdWIiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20ifQ.WaTB_ugEvjzUySYalWCEPP3rCfEPFJ4Y9-x_h0ogCyo

###

# Get list of all carts
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/carts/all

###

# Get a cart by id 
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/carts/3

###

# Update a cart
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/carts/4/update
content-type: application/json

{
    "items": [
        { "product_id": 4, "quantity": 2 }
    ]
}

###

# Create a cart
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/carts/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6Niwicm9sZSI6IkN1c3RvbWVyIiwiZW1haWwiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoZXJyeSIsImlhdCI6MTYzNzgyNTIzNywiZXhwIjoxNjM3ODI2MTM3LCJzdWIiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20ifQ.UOJF8SjN93uOlsU5L7wJS0zif_7icfnDP0q1DUWHIQs

{
    "items": [
        { "product_id": 4, "quantity": 1 }
    ]
}

###

# Update a user's cart

PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/carts/update
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6Niwicm9sZSI6IkN1c3RvbWVyIiwiZW1haWwiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoZXJyeSIsImlhdCI6MTYzNzgyNTIzNywiZXhwIjoxNjM3ODI2MTM3LCJzdWIiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20ifQ.UOJF8SjN93uOlsU5L7wJS0zif_7icfnDP0q1DUWHIQs

{
    "items": [
        { "product_id": 4, "quantity": 2 }
    ]
}

###

# Delete cart
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %APP_PORT}}/carts/2/delete

###

