# REST Client - https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###

# Get list of all users
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODc5ODU2MiwiZXhwIjoxNjM4Nzk5NDYyLCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.s8DdfJgOnN5XXo-2JGwr4gLeWxbNfKdh3E2XNFpO4pA

###

# Get list of all admin users
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/admins
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODc5ODU2MiwiZXhwIjoxNjM4Nzk5NDYyLCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.s8DdfJgOnN5XXo-2JGwr4gLeWxbNfKdh3E2XNFpO4pA

###

# Get list of all customers
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/customers
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODc5ODU2MiwiZXhwIjoxNjM4Nzk5NDYyLCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.s8DdfJgOnN5XXo-2JGwr4gLeWxbNfKdh3E2XNFpO4pA

###

# Get a specific user
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/5

###

# Create admin
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/create
content-type: application/json

{
    "firstname": "Baby",
    "lastname": "Star",
    "email": "star@gmail.com",
    "type": "Admin",
    "username": "baby",
    "password": "password",
    "federated_login": 0,
    "billing_address": "SG",
    "shipping_address": "SG"
}

###

# Create user
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/create
content-type: application/json

{
    "firstname": "Cherry",
    "lastname": "Blue",
    "email": "blue.cherry@gmail.com",
    "type": "Customer",
    "username": "cherry",
    "password": "password",
    "federated_login": 0,
    "billing_address": "SG",
    "shipping_address": "SG"
}

###

# Get info of authenticated user
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/info
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6Niwicm9sZSI6IkN1c3RvbWVyIiwiZW1haWwiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoZXJyeSIsImlhdCI6MTYzNzgzNzIzNCwiZXhwIjoxNjM3ODM4MTM0LCJzdWIiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20ifQ.B2QCOau0rSPr-KfoTYivNDA0Pn-ud7jH4DWvTVRYlaE

###

# Update user
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/3/update
content-type: application/json

{
    "firstname": "Darren",
    "lastname": "Poh",
    "email": "darpohsh@gmail.com",
    "type": "Admin",
    "username": null,
    "password": null,
    "federated_login": 0,
    "billing_address": "Bedok SG",
    "shipping_address": "SG"
}

###

# Delete user

DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/5/delete
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzOTAyNTYxNCwiZXhwIjoxNjM5MDI2NTE0LCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.ZCdG0JZirhgRIHx3mjcuO5tSGN9ux1jhe7JsSZyebrE

###

DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/delete
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6Nywicm9sZSI6IkN1c3RvbWVyIiwiZW1haWwiOiJzdGFyQGFiLmNvbSIsInVzZXJuYW1lIjoic3RhciIsImlhdCI6MTYzOTAzODEyOSwiZXhwIjoxNjM5MDM5MDI5LCJzdWIiOiJzdGFyQGFiLmNvbSJ9.bRwTKQRs4gpwkI4VDuac5TtoxfYQLTSPxvPg3aPA670

{
    "password": "password1"
}


###

# Authenticate using email/password

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/authenticate
content-type: application/json

{
    "username": "admin@your-company.com",
    "password": "password"
}

###

# Authenticate as admin using username/password

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/authenticate
content-type: application/json

{
    "username": "admin",
    "password": "password"
}

###

# Authenticate as customer using username/password

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/authenticate
content-type: application/json

{
    "username": "star",
    "password": "password1"
}

###

# Get new access token using refresh token

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/refresh
content-type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIn0.eyJpZCI6MSwiaWF0IjoxNjM4NjgxMjM1LCJleHAiOjE2MzkyODYwMzUsInN1YiI6ImFkbWluQHlvdXItY29tcGFueS5jb20ifQ.tRO8iEh_YIobHubR8cGse9UllZRVcDYJ6l9aeKsDCBo"
}

###

# Logout

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/logout
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6NSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJzdGFyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYmFieSIsImlhdCI6MTYzNzY1MzE1MCwiZXhwIjoxNjM3NjU0MDUwLCJzdWIiOiJzdGFyQGdtYWlsLmNvbSJ9.59Q90JqeeLHzBZURw-WCXF9StXhwvO9J4AljY5sli_o

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJyZWZyZXNoX3Rva2VuIn0.eyJpZCI6NSwiaWF0IjoxNjM3NjUzMTUwLCJleHAiOjE2MzgyNTc5NTAsInN1YiI6InN0YXJAZ21haWwuY29tIn0.TDolo31kPMmrazMN9Z42yZGAU0jd2OYHJNrbfsHeqnk"
}

###

# Change password

PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/users/5/change-password
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6NSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJzdGFyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYmFieSIsImlhdCI6MTYzNzU5NTMyMiwiZXhwIjoxNjM3NTk2MjIyLCJzdWIiOiJzdGFyQGdtYWlsLmNvbSJ9.BYepT8ScwD06XEZIuXz_hoCACXSbxg-tPRs_YyO-vD4


{
    "current_password": "password1",
    "new_password": "password"
}

###

# Get list of all categories
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/categories

###

# Get a specific category
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/categories/6

###

# Create category
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/categories/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODc1NDA5MywiZXhwIjoxNjM4NzU0OTkzLCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.07RSnIuTQh66SYZPbHWOEZNjVI0BYhtMwLzlpcbwzDg

{
    "name": "Test Shoes"
}

###

# Update category
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/categories/6/update
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODYyNjY3MCwiZXhwIjoxNjM4NjI3NTcwLCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.0eyoze-SgLHQ4ln2a4OSpBbwEtaeXNg9GHhzmhBRV80

{
    "name": "Test Shoes 2"
}

###

# Delete category
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/categories/6/delete
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODYyNzg4MSwiZXhwIjoxNjM4NjI4NzgxLCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.lFvNI9zued3DDu3v74cg9Bor2iRSG1lYyvkoVCaGBdw

###

# Get list of all designers
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/designers

###

# Get a specific designer
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/designers/2

###

# Update designer
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/designers/1/update
content-type: application/json

{
    "name": "Prada 1"
}

###

# Delete designer
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/designers/1/delete

###

# Create designer
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/designers/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODc1NDA5MywiZXhwIjoxNjM4NzU0OTkzLCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.07RSnIuTQh66SYZPbHWOEZNjVI0BYhtMwLzlpcbwzDg

{
    "name": "Dolce Gabbanna"
}

###

# Get list of all insurances
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/insurances

###

# Get a specific insurance
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/insurances/1

###

# Update insurance
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/insurances/1/update
content-type: application/json

{
    "policy_date": "2019-01-29",
    "claim_date": "2020-12-02",
    "coverage_amount": 300
}

###

# Delete a specific insurance
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/insurances/1/delete

###

# Create insurance
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/insurances/create
content-type: application/json

{
    "policy_date": "2019-01-30",
    "claim_date": "2020-12-01",
    "coverage_amount": 350
}

###

# Get list of all products
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products

###

# Get list of all products with search criteria
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products?tag_id=2

###

# Get list of product conditions
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products/conditions

###

# Get a specific product
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products/4

###

# Update a specific product
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products/2000/update
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODYxMTY1OSwiZXhwIjoxNjM4NjEyNTU5LCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.gtFlklnOZ9Ijcjb6VaGr-PcgaJgtu_ZZrtaQS2-b4nw

{
    "designer_id": 2,
    "category_id": 2,
    "insurance_id": 2,
    "name": "Prada Bag 2011",
    "retail_price": 150,
    "selling_price": 90,
    "description": "XX",
    "specifications": "",
    "condition": "",
    "condition_description": "",
    "sku": "",
    "quantity": 1,
    "authenticity": true,
    "product_image_1": "",
    "product_image_2": "",
    "product_gallery_1": "",
    "product_gallery_2": "",
    "product_gallery_3": "",
    "product_gallery_4": "",
    "product_gallery_5": "",
    "product_gallery_6": "",
    "product_gallery_7": "",
    "product_gallery_8": "",
    "tags": "2"
}



###

# Delete a specific product
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products/3/delete
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODYxMTY1OSwiZXhwIjoxNjM4NjEyNTU5LCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.gtFlklnOZ9Ijcjb6VaGr-PcgaJgtu_ZZrtaQS2-b4nw

###

# Create product
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODEwNTAzMSwiZXhwIjoxNjM4MTA1OTMxLCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.UVaVSUZS6IQcMe9aeXHipwz_f8qtmyR8FiO4z_01QYU

{
    "designer_id": 2,
    "category_id": 2,
    "insurance_id": 2,
    "name": "Prada Bag 2012",
    "retail_price": 155,
    "selling_price": 120,
    "description": "xx",
    "specifications": "",
    "condition": "",
    "condition_description": "",
    "sku": "",
    "quantity": 1,
    "authenticity": true,
    "product_image_1": "",
    "product_image_2": "",
    "product_gallery_1": "",
    "product_gallery_2": "",
    "product_gallery_3": "",
    "product_gallery_4": "",
    "product_gallery_5": "",
    "product_gallery_6": "",
    "product_gallery_7": "",
    "product_gallery_8": "",
    "tags": "2"
}

###

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/products/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODAyNTYxNSwiZXhwIjoxNjM4MDI2NTE1LCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.8S6MMM75F3wXk7yPgEPPYAI9xHuozBrHGj_19URmxj4

{"designer_id":"7","category_id":"4","name":"Xcode","retail_price":"150","selling_price":"120","condition":"Fair","condition_description":"XX","quantity":"1","authenticity":"1","product_image_1":"http://res.cloudinary.com/drkdludjy/image/upload/v1638025403/w5a8j0dw7gi6zw63h6bo.jpg","product_image_2":"http://res.cloudinary.com/drkdludjy/image/upload/v1638025415/hvas9dfllubaz40eiihx.jpg","product_gallery_1":"http://res.cloudinary.com/drkdludjy/image/upload/v1638025421/jx1hj1lnqzf4zgw7bnat.jpg","product_gallery_2":"http://res.cloudinary.com/drkdludjy/image/upload/v1638025429/ehyoxaalcn1ayzbibybl.jpg","product_gallery_3":"","product_gallery_4":"","product_gallery_5":"","product_gallery_6":"","product_gallery_7":"","product_gallery_8":"","tags":"1,3"}

###

# Get list of all tags
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/tags

###

# Get a specific tag
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/tags/1

###

# Create tag
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/tags/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODc2MjM3MSwiZXhwIjoxNjM4NzYzMjcxLCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.pqxMwoGLZ_HxslAvNkJO6Hl9DTstqQRO-z_TMlgF4Rk

{
    "name": "X Collaboration"
}

###

# Update tag
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/tags/2/update
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6NSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJzdGFyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYmFieSIsImlhdCI6MTYzNzY2NjA4OSwiZXhwIjoxNjM3NjY2OTg5LCJzdWIiOiJzdGFyQGdtYWlsLmNvbSJ9.o-W2ZluOPTB49b9dYVlUuzA9DLqk7dgW07ZOSdWOyIs

{
    "name": "New Arrival"
}

###

# Delete tag
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/tags/1/delete
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6NSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJzdGFyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYmFieSIsImlhdCI6MTYzNzY2NjA4OSwiZXhwIjoxNjM3NjY2OTg5LCJzdWIiOiJzdGFyQGdtYWlsLmNvbSJ9.o-W2ZluOPTB49b9dYVlUuzA9DLqk7dgW07ZOSdWOyIs

###

# Get cart for authenticated user
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/mycart
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6Miwicm9sZSI6IkN1c3RvbWVyIiwiZW1haWwiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoZXJyeSIsImlhdCI6MTYzODg5NTE4NiwiZXhwIjoxNjM4ODk2MDg2LCJzdWIiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20ifQ.IV_cyejcyLZzdaT-R9u37YKAZI_S3UDGUkAfWqAvagw

###

# Get list of all carts
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/all
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODQyMTk4NSwiZXhwIjoxNjM4NDIyODg1LCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.MGE-Yh25cAoFdje9OCMCjrRUROyiwtGC-s60JQmhXN4

###

# Get a cart by id 
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/52

###

# Update a cart
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/34/update
content-type: application/json

{
    "items": [
        { "product_id": 1, "quantity": 3 },
        { "product_id": 2, "quantity": 4 }
    ]
}

###

# Create a cart
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODQyNTU0OSwiZXhwIjoxNjM4NDI2NDQ5LCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.ikHqAFy8KAd6tKNiOugLz3pDOtFz7qLW7Wd7nzo-uxI

{
    "items": [
        { "product_id": 2, "quantity": 3 }
    ]
}

###

# Create a cart for anonymous
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/create
content-type: application/json

{
    "items": [
        { "product_id": 2, "quantity": 1 }
    ]
}



###

# Update a user's cart

PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/update
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6Niwicm9sZSI6IkN1c3RvbWVyIiwiZW1haWwiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoZXJyeSIsImlhdCI6MTYzNzgyNTIzNywiZXhwIjoxNjM3ODI2MTM3LCJzdWIiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20ifQ.UOJF8SjN93uOlsU5L7wJS0zif_7icfnDP0q1DUWHIQs

{
    "items": [
        { "product_id": 4, "quantity": 2 }
    ]
}

###

# Update quantity of a cart item

PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/34/update/2
content-type: application/json

{
    "quantity": 2
}

###

# Update ownership of a cart

PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/35/own
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6Miwicm9sZSI6IkN1c3RvbWVyIiwiZW1haWwiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoZXJyeSIsImlhdCI6MTYzODQ1NjIwNSwiZXhwIjoxNjM4NDU3MTA1LCJzdWIiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20ifQ.aU2DCX4HRpCtxuWTgzWwDo0Oa53ftKxkLen-a0QUqqA

###

# Delete cart
DELETE {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/2/delete

###

# Checkout

POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/checkout
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6Miwicm9sZSI6IkN1c3RvbWVyIiwiZW1haWwiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoZXJyeSIsImlhdCI6MTYzODQ1NzE3NiwiZXhwIjoxNjM4NDU4MDc2LCJzdWIiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20ifQ.rieZSf33NJLVXhVV1r3TP1Fh4pkRj0JpK6vo32pqDnA

{
    "success_url": "https://4000-pink-giraffe-lsp7nj70.ws-us20.gitpod.io/checkout/success",
    "cancel_url": "https://4000-pink-giraffe-lsp7nj70.ws-us20.gitpod.io/checkout/error"
}

###

# Get list of all orders
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/orders
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODc5NzIwMiwiZXhwIjoxNjM4Nzk4MTAyLCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.7II0KIFl2WA9ciGYdBorg87vZgq3kiBlCC4OCB-DJ5o

###

# Get list of valid order statuses
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/orders/statuses

###

# Get list of shipment/courier providers
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/orders/shipment-providers

###

# Get an order
GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/orders/3
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODUwMzU1NywiZXhwIjoxNjM4NTA0NDU3LCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.HGyB_4MJ7TJ10mUibTD9jTMD1Xa302W7-p4MrgZotNU

###

# Update an order
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/orders/3
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODUwMzU1NywiZXhwIjoxNjM4NTA0NDU3LCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.HGyB_4MJ7TJ10mUibTD9jTMD1Xa302W7-p4MrgZotNU

{
    "status": "Delivered",
    "comment": "Testing 2.."
}

###

# Get all consignments

GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/consignments
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODY5MDQ2NywiZXhwIjoxNjM4NjkxMzY3LCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.5rigw322kT1nnA0FsvdxsHYUjdlB-FT4WqKC6SlBMEY


###

# Get valid consignment statuses

GET {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/consignments/statuses


###

# Create consigment
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/consignments/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6Miwicm9sZSI6IkN1c3RvbWVyIiwiZW1haWwiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImNoZXJyeSIsImlhdCI6MTYzODY4MDUyNywiZXhwIjoxNjM4NjgxNDI3LCJzdWIiOiJibHVlLmNoZXJyeUBnbWFpbC5jb20ifQ.T5ITqV4Y1p9qCRMI4k3SbxemCfVESET4XJe-WMZJX3E

{
    "designer_id": 2,
    "category_id": 2,
    "name": "Rolex 2012",
    "selling_price": 120,
    "specifications": "45cm by 60cm",
    "condition": "good",
    "condition_description": "Good with no scatches",
    "product_gallery_1": "",
    "product_gallery_2": "",
    "product_gallery_3": "",
    "product_gallery_4": "",
    "product_gallery_5": "",
    "product_gallery_6": "",
    "product_gallery_7": "",
    "product_gallery_8": null
}

###

# Update a consignment
PUT {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/consignments/1/update
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInRva2VuX3R5cGUiOiJhY2Nlc3NfdG9rZW4ifQ.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYzODY4MTIzNSwiZXhwIjoxNjM4NjgyMTM1LCJzdWIiOiJhZG1pbkB5b3VyLWNvbXBhbnkuY29tIn0.hTGW2PYU3BcUUtS9cg4LJ-RbQ4YR31KIwkcVJyfDYUw

{
    "status": "Initial Evaluation",
    "comment": "some comments from evaluation..."
}

###

# Test
POST {{$dotenv %APP_HOSTNAME}}:{{$dotenv %PORT}}/carts/test1

###
